<a href="https://colab.research.google.com/github/duke-sunshine/NYU_Econometrics_Summer2021/blob/main/Economics_Milestone5_Causal_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preparation

Story Background: https://www.gemini.com/cryptopedia/the-dao-hack-makerdao

Event: July 20, 2016, at block 192,000

[Data Metrics](https://github.com/coinmetrics-io/data/blob/master/csv/metrics.csv)

In [ ]:
import pandas as pd
import numpy as np

###import the data for Ethereum

In [ ]:
df_eth=pd.read_csv("https://raw.githubusercontent.com/coinmetrics-io/data/master/csv/eth.csv")
df_eth.head()

         time  AdrActCnt  ...  VtyDayRet180d  VtyDayRet30d
0  2015-07-30     9206.0  ...            NaN           NaN
1  2015-07-31      424.0  ...            NaN           NaN
2  2015-08-01      413.0  ...            NaN           NaN
3  2015-08-02      432.0  ...            NaN           NaN
4  2015-08-03      444.0  ...            NaN           NaN

[5 rows x 139 columns]

In [ ]:
df_eth['time']=pd.to_datetime(df_eth['time'])
df_eth.dtypes

time                datetime64[ns]
AdrActCnt                  float64
AdrBal1in100KCnt           float64
AdrBal1in100MCnt           float64
AdrBal1in10BCnt            float64
                         ...
TxTfrValMedNtv             float64
TxTfrValMedUSD             float64
VelCur1yr                  float64
VtyDayRet180d              float64
VtyDayRet30d               float64
Length: 139, dtype: object

In [ ]:
df_eth['Type'] = 'eth'
df_eth.head()

        time  AdrActCnt  AdrBal1in100KCnt  ...  VtyDayRet180d  VtyDayRet30d  Type
0 2015-07-30     9206.0            5685.0  ...            NaN           NaN   eth
1 2015-07-31      424.0            5692.0  ...            NaN           NaN   eth
2 2015-08-01      413.0            5699.0  ...            NaN           NaN   eth
3 2015-08-02      432.0            5708.0  ...            NaN           NaN   eth
4 2015-08-03      444.0            5715.0  ...            NaN           NaN   eth

[5 rows x 140 columns]

### Import the Data for Ethereum Classic

In [ ]:
df_etc=pd.read_csv("https://raw.githubusercontent.com/coinmetrics-io/data/master/csv/etc.csv")
df_etc.head()

         time  AdrActCnt  ...  VtyDayRet180d  VtyDayRet30d
0  2016-07-20    21680.0  ...            NaN           NaN
1  2016-07-21    17037.0  ...            NaN           NaN
2  2016-07-22    13208.0  ...            NaN           NaN
3  2016-07-23     9838.0  ...            NaN           NaN
4  2016-07-24    14910.0  ...            NaN           NaN

[5 rows x 134 columns]

In [ ]:
### change to dateime
df_etc['time']=pd.to_datetime(df_etc['time'])
df_etc.dtypes

time                datetime64[ns]
AdrActCnt                  float64
AdrBal1in100KCnt           float64
AdrBal1in100MCnt           float64
AdrBal1in10BCnt            float64
                         ...
TxTfrValMedNtv             float64
TxTfrValMedUSD             float64
VelCur1yr                  float64
VtyDayRet180d              float64
VtyDayRet30d               float64
Length: 134, dtype: object

In [ ]:
df_etc['Type'] = 'etc'
df_etc.head()

        time  AdrActCnt  AdrBal1in100KCnt  ...  VtyDayRet180d  VtyDayRet30d  Type
0 2016-07-20    21680.0            5491.0  ...            NaN           NaN   etc
1 2016-07-21    17037.0            5471.0  ...            NaN           NaN   etc
2 2016-07-22    13208.0            5497.0  ...            NaN           NaN   etc
3 2016-07-23     9838.0            5499.0  ...            NaN           NaN   etc
4 2016-07-24    14910.0            5304.0  ...            NaN           NaN   etc

[5 rows x 135 columns]

# Regression Discontinguity

https://youtu.be/TfKwgGT2fSM

### create the identifier varaible for Dao Hack

In [ ]:
from datetime import date

In [ ]:
df_eth ['After_DaoHack'] =df_eth['time'].apply(lambda x: 1 if x>= date(2016,7,20) else 0)
df_eth[df_eth.time.dt.date>=date(2016,7,18)].head()

          time  AdrActCnt  AdrBal1in100KCnt  ...  VtyDayRet30d  Type  After_DaoHack
354 2016-07-18    18988.0            6564.0  ...      0.056129   eth              0
355 2016-07-19    26614.0            5492.0  ...      0.054430   eth              0
356 2016-07-20    25428.0            5730.0  ...      0.055036   eth              1
357 2016-07-21    22477.0            5866.0  ...      0.051285   eth              1
358 2016-07-22    24563.0            5917.0  ...      0.058285   eth              1

[5 rows x 141 columns]

In [ ]:
df_eth['days']=df_eth.index
df_eth.head()

        time  AdrActCnt  AdrBal1in100KCnt  ...  Type  After_DaoHack  days
0 2015-07-30     9206.0            5685.0  ...   eth              0     0
1 2015-07-31      424.0            5692.0  ...   eth              0     1
2 2015-08-01      413.0            5699.0  ...   eth              0     2
3 2015-08-02      432.0            5708.0  ...   eth              0     3
4 2015-08-03      444.0            5715.0  ...   eth              0     4

[5 rows x 142 columns]

### normalize the data

In [ ]:
df_eth['days'][df_eth.time.dt.date==date(2016,7,20)]

356    356
Name: days, dtype: int64

In [ ]:
df_eth['days']=df_eth['days']-356
df_eth[df_eth.time.dt.date>=date(2016,7,18)].head()

          time  AdrActCnt  AdrBal1in100KCnt  ...  Type  After_DaoHack  days
354 2016-07-18    18988.0            6564.0  ...   eth              0    -2
355 2016-07-19    26614.0            5492.0  ...   eth              0    -1
356 2016-07-20    25428.0            5730.0  ...   eth              1     0
357 2016-07-21    22477.0            5866.0  ...   eth              1     1
358 2016-07-22    24563.0            5917.0  ...   eth              1     2

[5 rows x 142 columns]

## create the regression function

https://www.statsmodels.org/stable/index.html

In [ ]:
 import statsmodels.api as sm
 import statsmodels.formula.api as smf

In [ ]:
results = smf.ols('PriceUSD ~ 1+ After_DaoHack +days+TxTfrValAdjUSD ', data=df_eth).fit()

In [ ]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               PriceUSD   R-squared:                       0.703
Model:                            OLS   Adj. R-squared:                  0.702
Method:                 Least Squares   F-statistic:                     1681.
Date:                Tue, 15 Jun 2021   Prob (F-statistic):               0.00
Time:                        14:51:30   Log-Likelihood:                -15328.
No. Observations:                2138   AIC:                         3.066e+04
Df Residuals:                    2134   BIC:                         3.069e+04
Df Model:                           3
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         49.7467     17.102      2.909      0.004      16.209      83.285
After_DaoHack    -23.6975     24.176     -0.980      0.327     -71.109      23.714
days               0.2583      0.016     16.636      0.000       0.228       0.289
TxTfrValAdjUSD  1.008e-07   1.88e-09     53.571      0.000    9.71e-08    1.04e-07
==============================================================================
Omnibus:                     2503.831   Durbin-Watson:                   1.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          2332054.006
Skew:                          -5.182   Prob(JB):                         0.00
Kurtosis:                     164.465   Cond. No.                     1.76e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.76e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
results = smf.ols('PriceUSD ~ 1+ After_DaoHack + days +After_DaoHack*days +TxTfrValAdjUSD', data=df_eth).fit()

In [ ]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               PriceUSD   R-squared:                       0.703
Model:                            OLS   Adj. R-squared:                  0.702
Method:                 Least Squares   F-statistic:                     1262.
Date:                Tue, 15 Jun 2021   Prob (F-statistic):               0.00
Time:                        14:51:30   Log-Likelihood:                -15327.
No. Observations:                2138   AIC:                         3.066e+04
Df Residuals:                    2133   BIC:                         3.069e+04
Df Model:                           4
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             11.5152     33.840      0.340      0.734     -54.848      77.878
After_DaoHack         13.0086     37.019      0.351      0.725     -59.588      85.605
days                   0.0385      0.169      0.229      0.819      -0.292       0.369
After_DaoHack:days     0.2216      0.169      1.309      0.191      -0.110       0.554
TxTfrValAdjUSD      1.007e-07   1.88e-09     53.502      0.000     9.7e-08    1.04e-07
==============================================================================
Omnibus:                     2501.011   Durbin-Watson:                   1.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          2321078.664
Skew:                          -5.171   Prob(JB):                         0.00
Kurtosis:                     164.084   Cond. No.                     3.06e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.06e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

# Difference in Difference

https://towardsdatascience.com/causal-inference-101-difference-in-differences-1fbbb0f55e85

### prepare the datasets

In [ ]:
Columns =["time","PriceUSD","TxTfrValAdjUSD","FeeMedUSD","RevUSD","GasLmtTxMean","Type"]
df_eth =df_eth[Columns]
df_etc =df_etc[Columns]

In [ ]:
df_etc =df_etc.dropna()
df_etc.head()

        time  PriceUSD  TxTfrValAdjUSD  ...         RevUSD   GasLmtTxMean  Type
5 2016-07-25  0.609005    3.988031e+06  ...   19053.076289  128512.450456   etc
6 2016-07-26  2.550458    2.138461e+07  ...  117166.149612  106473.058865   etc
7 2016-07-27  1.619800    1.597548e+07  ...   53581.634999  121838.776100   etc
8 2016-07-28  1.727024    2.210299e+07  ...   57859.069868  118155.032968   etc
9 2016-07-29  1.649872    1.257784e+07  ...   58069.745834  108353.172803   etc

[5 rows x 7 columns]

In [ ]:
df_eth =df_eth[df_eth.time.dt.date>=date(2016,7,25)]
df_etc =df_etc[df_etc.time.dt.date>=date(2016,7,25)]

In [ ]:
df_eth=df_eth.reset_index()
df_etc=df_etc.reset_index()

In [ ]:
df_eth["days"]=df_eth.index
df_eth.head()

   index       time   PriceUSD  ...   GasLmtTxMean  Type  days
0    361 2016-07-25  13.840295  ...  116866.529623   eth     0
1    362 2016-07-26  11.963285  ...  106522.289666   eth     1
2    363 2016-07-27  13.061564  ...  126615.358103   eth     2
3    364 2016-07-28  12.888203  ...  133514.917908   eth     3
4    365 2016-07-29  12.878013  ...  139836.829202   eth     4

[5 rows x 9 columns]

In [ ]:
df_etc["days"]=df_etc.index
df_etc.head()

   index       time  PriceUSD  ...   GasLmtTxMean  Type  days
0      5 2016-07-25  0.609005  ...  128512.450456   etc     0
1      6 2016-07-26  2.550458  ...  106473.058865   etc     1
2      7 2016-07-27  1.619800  ...  121838.776100   etc     2
3      8 2016-07-28  1.727024  ...  118155.032968   etc     3
4      9 2016-07-29  1.649872  ...  108353.172803   etc     4

[5 rows x 9 columns]

In [ ]:
df = pd.concat([df_eth, df_etc], axis=0)
df.head()

   index       time   PriceUSD  ...   GasLmtTxMean  Type  days
0    361 2016-07-25  13.840295  ...  116866.529623   eth     0
1    362 2016-07-26  11.963285  ...  106522.289666   eth     1
2    363 2016-07-27  13.061564  ...  126615.358103   eth     2
3    364 2016-07-28  12.888203  ...  133514.917908   eth     3
4    365 2016-07-29  12.878013  ...  139836.829202   eth     4

[5 rows x 9 columns]

In [ ]:
df["etc"]=df["Type"].apply(lambda x: 1 if x=="etc" else 0)
df.head()

   index       time   PriceUSD  TxTfrValAdjUSD  ...   GasLmtTxMean  Type  days etc
0    361 2016-07-25  13.840295    1.100270e+08  ...  116866.529623   eth     0   0
1    362 2016-07-26  11.963285    1.962552e+08  ...  106522.289666   eth     1   0
2    363 2016-07-27  13.061564    1.251180e+08  ...  126615.358103   eth     2   0
3    364 2016-07-28  12.888203    8.846049e+07  ...  133514.917908   eth     3   0
4    365 2016-07-29  12.878013    5.242804e+07  ...  139836.829202   eth     4   0

[5 rows x 10 columns]

### run the regression

Treatment: ETC hard-fork

In [ ]:
 import statsmodels.api as sm
 import statsmodels.formula.api as smf

In [ ]:
results = smf.ols('PriceUSD ~ 1+ etc +days+TxTfrValAdjUSD+FeeMedUSD+RevUSD+GasLmtTxMean', data=df).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               PriceUSD   R-squared:                       0.973
Model:                            OLS   Adj. R-squared:                  0.973
Method:                 Least Squares   F-statistic:                 2.105e+04
Date:                Tue, 15 Jun 2021   Prob (F-statistic):               0.00
Time:                        14:59:16   Log-Likelihood:                -20687.
No. Observations:                3572   AIC:                         4.139e+04
Df Residuals:                    3565   BIC:                         4.143e+04
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept        -47.4874      3.637    -13.056      0.000     -54.619     -40.356
etc              -14.4759      3.094     -4.679      0.000     -20.542      -8.410
days               0.0654      0.003     23.752      0.000       0.060       0.071
TxTfrValAdjUSD  5.085e-09   7.52e-10      6.762      0.000    3.61e-09    6.56e-09
FeeMedUSD       -124.2947      1.757    -70.729      0.000    -127.740    -120.849
RevUSD          5.711e-05   3.75e-07    152.196      0.000    5.64e-05    5.78e-05
GasLmtTxMean   -3.367e-06   9.95e-06     -0.338      0.735   -2.29e-05    1.61e-05
==============================================================================
Omnibus:                     3667.170   Durbin-Watson:                   0.510
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1640464.397
Skew:                          -4.300   Prob(JB):                         0.00
Kurtosis:                     107.634   Cond. No.                     1.05e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.05e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
results = smf.ols('PriceUSD ~ 1+ etc +days +etc*days+TxTfrValAdjUSD+FeeMedUSD+RevUSD+GasLmtTxMean', data=df).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               PriceUSD   R-squared:                       0.978
Model:                            OLS   Adj. R-squared:                  0.978
Method:                 Least Squares   F-statistic:                 2.260e+04
Date:                Tue, 15 Jun 2021   Prob (F-statistic):               0.00
Time:                        14:59:42   Log-Likelihood:                -20294.
No. Observations:                3572   AIC:                         4.060e+04
Df Residuals:                    3564   BIC:                         4.065e+04
Df Model:                           7
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept       -111.3056      3.908    -28.480      0.000    -118.968    -103.643
etc              107.9392      4.980     21.676      0.000      98.176     117.702
days               0.1478      0.004     39.728      0.000       0.141       0.155
etc:days          -0.1459      0.005    -29.593      0.000      -0.156      -0.136
TxTfrValAdjUSD  4.288e-09   6.74e-10      6.359      0.000    2.97e-09    5.61e-09
FeeMedUSD       -129.8503      1.586    -81.879      0.000    -132.960    -126.741
RevUSD            5.7e-05   3.36e-07    169.506      0.000    5.63e-05    5.77e-05
GasLmtTxMean    -1.37e-05   8.93e-06     -1.535      0.125   -3.12e-05     3.8e-06
==============================================================================
Omnibus:                     3818.674   Durbin-Watson:                   0.562
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          2184150.593
Skew:                          -4.561   Prob(JB):                         0.00
Kurtosis:                     123.797   Cond. No.                     1.62e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.62e+10. This might indicate that there are
strong multicollinearity or other numerical problems.